project:
  type: website

website:
  title: "r-collection"
  navbar:
    left:
      - href: index.qmd
        text: ggplot2
      - regression.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

